backoffice/routes/backoffice.py
from flask import Blueprint, render_template, url_for, redirect, request
from flask_socketio import emit

from backoffice.aco.aco import ant_system
from config import socketIO, trips_repository, aco_configurations_repository
from routes.trip import nodes


bp = Blueprint("backoffice", __name__, url_prefix="/backoffice")


@bp.route("/")
def home():
    return render_template("backoffice/index.html")


@bp.route("/trip/search")
def search_trip():
    data = [
        {"from": "A", "to": "E", "feromone": 1},
        {"from": "A", "to": "F", "feromone": 1},
        {"from": "A", "to": "B", "feromone": 1},
        {"from": "B", "to": "F", "feromone": 1},
        {"from": "B", "to": "C", "feromone": 1},
        {"from": "B", "to": "G", "feromone": 1},
        {"from": "C", "to": "G", "feromone": 1},
        {"from": "C", "to": "D", "feromone": 1},
        {"from": "C", "to": "H", "feromone": 1},
        {"from": "D", "to": "H", "feromone": 1},
        {"from": "E", "to": "F", "feromone": 1},
        {"from": "E", "to": "I", "feromone": 1},
        {"from": "E", "to": "J", "feromone": 1},
        {"from": "F", "to": "J", "feromone": 1},
        {"from": "F", "to": "G", "feromone": 1},
        {"from": "F", "to": "K", "feromone": 1},
        {"from": "G", "to": "K", "feromone": 1},
        {"from": "G", "to": "H", "feromone": 1},
        {"from": "G", "to": "L", "feromone": 1},
        {"from": "H", "to": "L", "feromone": 1},
        {"from": "I", "to": "J", "feromone": 1},
        {"from": "I", "to": "M", "feromone": 1},
        {"from": "I", "to": "N", "feromone": 1},
        {"from": "J", "to": "K", "feromone": 1},
        {"from": "J", "to": "N", "feromone": 1},
        {"from": "J", "to": "O", "feromone": 1},
        {"from": "K", "to": "L", "feromone": 1},
        {"from": "K", "to": "O", "feromone": 1},
        {"from": "K", "to": "P", "feromone": 1},
        {"from": "L", "to": "P", "feromone": 1},
        {"from": "M", "to": "N", "feromone": 1},
        {"from": "N", "to": "O", "feromone": 1},
        {"from": "O", "to": "P", "feromone": 1},
    ]
    trips = trips_repository.get_all_trips()

    return render_template("backoffice/search_trip.html",
                           data=data,
                           trips=to_trips_output(trips))


@socketIO.on("search_trip")
def handle_search_trip(data):
    node_from = data["from"]
    if node_from not in nodes:
        emit('search_trip_finish', {"error": f"El nodo origen \"{node_from}\" ingresado es invalido"})
        return
    node_to = data["to"]
    if node_to not in nodes:
        emit('search_trip_finish', {"error": f"El nodo destino \"{node_to}\" ingresado es invalido"})
        return

    aco_configurations = aco_configurations_repository.get_configurations()
    iter_input = aco_configurations["iter"]
    debug = aco_configurations["debug"]
    evaporation_rate = aco_configurations["evaporation_rate"]

    trips = trips_repository.get_all_trips()
    if not trips:
        emit('search_trip_finish', {"best_trip": []})
        return

    best_trip = ant_system(node_from, node_to, trips, iter_input, evaporation_rate, debug)
    emit('search_trip_finish', {"best_trip": best_trip})


@bp.route("/trip/search/configs", methods=['POST'])
def save_search_trip_configs():
    iter_input = int(request.form["iter_input"])
    evaporation_rate = float(request.form["evaporation_rate"])
    debug = request.form["debug"] == "true"
    aco_configurations_repository.save_configurations(
        iter=iter_input,
        evaporation_rate=evaporation_rate,
        debug=debug
    )

    return {}


@bp.route("/trip/delete", methods=['POST'])
def delete_all_trips():
    trips_repository.delete_all_trips()
    return redirect(url_for("backoffice.search_trip"))


def to_trips_output(trips):
    trips_output = []
    for trip in trips:
        for i in range(len(trip) - 1):
            nodo = trip[i]
            nodo_sig = trip[i + 1]
            trips_output.append({"from": nodo, "to": nodo_sig})

    return trips_output

views/backoffice.py
from flask import Blueprint, render_template, url_for, redirect, request
from flask_socketio import emit

from aco.aco_backoffice import ant_system, elitist_ant_system, rank_ant_system
from config import socketIO, trips_repository, aco_configurations_repository
from views.trip import nodes


bp = Blueprint("backoffice", __name__, url_prefix="/backoffice")


@bp.route("/")
def home():
    return render_template("backoffice/index.html")


@bp.route("/trip/search")
def search_trip():
    data = [
        {"from": "A", "to": "E", "feromone": 1},
        {"from": "A", "to": "F", "feromone": 1},
        {"from": "A", "to": "B", "feromone": 1},
        {"from": "B", "to": "F", "feromone": 1},
        {"from": "B", "to": "C", "feromone": 1},
        {"from": "B", "to": "G", "feromone": 1},
        {"from": "C", "to": "G", "feromone": 1},
        {"from": "C", "to": "D", "feromone": 1},
        {"from": "C", "to": "H", "feromone": 1},
        {"from": "D", "to": "H", "feromone": 1},
        {"from": "E", "to": "F", "feromone": 1},
        {"from": "E", "to": "I", "feromone": 1},
        {"from": "E", "to": "J", "feromone": 1},
        {"from": "F", "to": "J", "feromone": 1},
        {"from": "F", "to": "G", "feromone": 1},
        {"from": "F", "to": "K", "feromone": 1},
        {"from": "G", "to": "K", "feromone": 1},
        {"from": "G", "to": "H", "feromone": 1},
        {"from": "G", "to": "L", "feromone": 1},
        {"from": "H", "to": "L", "feromone": 1},
        {"from": "I", "to": "J", "feromone": 1},
        {"from": "I", "to": "M", "feromone": 1},
        {"from": "I", "to": "N", "feromone": 1},
        {"from": "J", "to": "K", "feromone": 1},
        {"from": "J", "to": "N", "feromone": 1},
        {"from": "J", "to": "O", "feromone": 1},
        {"from": "K", "to": "L", "feromone": 1},
        {"from": "K", "to": "O", "feromone": 1},
        {"from": "K", "to": "P", "feromone": 1},
        {"from": "L", "to": "P", "feromone": 1},
        {"from": "M", "to": "N", "feromone": 1},
        {"from": "N", "to": "O", "feromone": 1},
        {"from": "O", "to": "P", "feromone": 1},
    ]
    trips = trips_repository.get_all_trips()

    return render_template("backoffice/search_trip.html",
                           data=data,
                           trips=to_trips_output(trips))


@socketIO.on("search_trip")
def handle_search_trip(data):
    node_from = data["from"]
    if node_from not in nodes:
        emit('search_trip_finish', {"error": f"El nodo origen \"{node_from}\" ingresado es invalido"})
        return
    node_to = data["to"]
    if node_to not in nodes:
        emit('search_trip_finish', {"error": f"El nodo destino \"{node_to}\" ingresado es invalido"})
        return

    trips = trips_repository.get_all_trips()
    if not trips:
        emit('search_trip_finish', {"best_trip": []})
        return

    aco_configurations = aco_configurations_repository.get_configurations()
    iter_input = aco_configurations["iter"]
    debug = aco_configurations["debug"]
    evaporation_rate = aco_configurations["evaporation_rate"]
    aco_algorithm = aco_configurations["aco_algorithm"]

    if aco_algorithm == "ant_system":
        best_trip = ant_system(node_from, node_to, trips, iter_input, evaporation_rate, debug)
    elif aco_algorithm == "elitist_ant_system":
        weight_best_tour_so_far = aco_configurations["weight_best_tour_so_far"]
        best_trip = elitist_ant_system(node_from, node_to, trips, iter_input, evaporation_rate, weight_best_tour_so_far, debug)
    elif aco_algorithm == "rank_ant_system":
        ants_per_iteration = aco_configurations["ants_per_iteration"]
        number_ants_to_rank = aco_configurations["number_ants_to_rank"]
        best_trip = rank_ant_system(node_from, node_to, trips, iter_input, ants_per_iteration, number_ants_to_rank, evaporation_rate, debug)
    else:
        best_trip = ant_system(node_from, node_to, trips, iter_input, evaporation_rate, debug)

    emit('search_trip_finish', {"best_trip": best_trip})


@bp.route("/trip/search/configs", methods=['POST'])
def save_search_trip_configs():
    iter_input = int(request.form["iter_input"])
    evaporation_rate = float(request.form["evaporation_rate"])
    debug = request.form["debug"] == "true"
    aco_algorithm = request.form["aco_algorithm"]
    weight_best_tour_so_far = int(request.form["weight_best_tour_so_far"])
    ants_per_iteration = int(request.form["ants_per_iteration"])
    number_ants_to_rank = int(request.form["number_ants_to_rank"])

    aco_configurations_repository.save_configurations(
        iter=iter_input,
        evaporation_rate=evaporation_rate,
        debug=debug,
        aco_algorithm=aco_algorithm,
        weight_best_tour_so_far=weight_best_tour_so_far,
        ants_per_iteration=ants_per_iteration,
        number_ants_to_rank=number_ants_to_rank
    )

    return {}


@bp.route("/trip/delete", methods=['POST'])
def delete_all_trips():
    trips_repository.delete_all_trips()
    return redirect(url_for("backoffice.search_trip"))


def to_trips_output(trips):
    trips_output = []
    for trip in trips:
        for i in range(len(trip) - 1):
            nodo = trip[i]
            nodo_sig = trip[i + 1]
            trips_output.append({"from": nodo, "to": nodo_sig})

    return trips_output

templates/backoffice/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} CarpooleArg {% endblock %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <style type="text/css">
        #container {
            min-width: 320px;
            max-width: 800px;
            margin: 0 auto;
            height: 500px;
        }
    </style>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('home') }}">Volver a Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('backoffice.search_trip') }}">Backoffice | Search trip</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('how') }}">How</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('how2') }}">How2</a>
        </li>
    </ul>

    <div class="container">
        {% block body %}{% endblock %}
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/networkgraph.js"></script>

    {% block script %}{% endblock %}
</body>
</html>

templates/backoffice/how.html
{% extends 'base.html' %}

{% block body %}
    <div id="container"></div>

    <a id="lanzar_hormiga" class="btn btn-outline-primary" role="button" aria-pressed="true">Lanzar hormiga</a>
    <a href="{{ url_for('reset') }}" class="btn btn-outline-danger" role="button" aria-pressed="true">Reset</a>
{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js"></script>

<script>
    const socket = io()

    $('#lanzar_hormiga').on('click', function() {
        chart.series[0].data.forEach(d => d.update({'color': null}))
        chart.redraw()
        socket.emit("lanzar_hormiga", "");
    });

    socket.on('avanzar_hormiga', function(link) {
        //console.log(link);
        //console.log(chart.series[0]['data']);

        var networkgraph_link = chart.series[0]['data'].filter(function(d) {
            return d['from'] == link['from'] && d['to'] == link['to'];
        })[0];
        networkgraph_link.update({'color': 'yellow'});

        chart.redraw();
    });

    socket.on('actualizar_feromona', function(link) {
        //console.log(link);

        var networkgraph_link = chart.series[0]['data'].filter(function(d) {
            return d['from'] == link['from'] && d['to'] == link['to'];
        })[0];
        networkgraph_link.update({'feromone': link['feromone']});
        chart.redraw();
    });
</script>

<script>
        var networkgraph_data = {{ data|tojson }};
        var chart = Highcharts.chart('container', {
            chart: {
                type: 'networkgraph'
            },
            series: [{
                dataLabels: {
                    enabled: true,
                    linkFormat: '{point.feromone}'
                },
                link: {
                    width: 2
                },
                marker: {
                    radius: 15
                },
                layoutAlgorithm: {
                    maxIterations: 1,
                    initialPositions: function() {
                        this.nodes.forEach((node, i) => {
                            //console.log(node);
                            if (node.id == 'A') {
                                node.plotX = 100;
                                node.plotY = 100;
                            }
                            if (node.id == 'B') {
                                node.plotX = 200;
                                node.plotY = 100;
                            }
                            if (node.id == 'H') {
                                node.plotX = 300;
                                node.plotY = 200;
                            }
                            if (node.id == 'C') {
                                node.plotX = 300;
                                node.plotY = 80;
                            }
                            if (node.id == 'D') {
                                node.plotX = 400;
                                node.plotY = 100;
                            }
                            if (node.id == 'E') {
                                node.plotX = 500;
                                node.plotY = 100;
                            }
                        });
                    }
                },
                data: networkgraph_data
            }]
    });
    </script>
{% endblock %}

templates/backoffice/how2.html
{% extends 'base.html' %}

{% block body %}
    <p id="iter">Iteracion: 0</p>

    <div id="container"></div>

    <a id="iniciar" class="btn btn-outline-primary" role="button" aria-pressed="true">Iniciar</a>
{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js"></script>

<script>
    const socket = io()

    $('#iniciar').on('click', function() {
        socket.emit("lanzar_hormiga2", "");
    })

    socket.on('lanzar_hormiga_reset', function(iter_num) {
        chart.series[0].data.forEach( d => d.update({'color': null}))
        chart.redraw()

        $('#iter').text("Iteracion: " + iter_num)
    });

    socket.on('avanzar_hormiga', function(link) {
        //console.log(link);
        //console.log(chart.series[0]['data']);

        var networkgraph_link = chart.series[0]['data'].filter(function(d) {
            return d['from'] == link['from'] && d['to'] == link['to'];
        })[0];
        networkgraph_link.update({'color': 'yellow'});

        chart.redraw();
    });

    socket.on('actualizar_feromona', function(link) {
        //console.log(link);

        var networkgraph_link = chart.series[0]['data'].filter(function(d) {
            return d['from'] == link['from'] && d['to'] == link['to'];
        })[0];
        networkgraph_link.update({'feromone': link['feromone']});
        chart.redraw();
    });
</script>

<script>
        var data = {{ data|tojson }}
        var chart = Highcharts.chart('container', {
        chart: {
            type: 'networkgraph'
        },
        title: {
            text: ""
        },
        series: [{
            dataLabels: {
                enabled: true,
                linkFormat: '{point.feromone}'
            },
            link: {
                width: 2
            },
            marker: {
                radius: 15
            },
            layoutAlgorithm: {
                maxIterations: 1,
                initialPositions: function() {
                    this.nodes.forEach((node, i) => {
                        //console.log(node);
                        if (node.id == 'A') {
                            node.plotX = 100;
                            node.plotY = 100;
                        }
                        if (node.id == 'B') {
                            node.plotX = 200;
                            node.plotY = 100;
                        }
                        if (node.id == 'H') {
                            node.plotX = 300;
                            node.plotY = 200;
                        }
                        if (node.id == 'C') {
                            node.plotX = 300;
                            node.plotY = 80;
                        }
                        if (node.id == 'D') {
                            node.plotX = 400;
                            node.plotY = 100;
                        }
                        if (node.id == 'E') {
                            node.plotX = 500;
                            node.plotY = 100;
                        }
                    });
                }
            },
            data: data
        }]
    });
    </script>
{% endblock %}

templates/backoffice/index.html
{% extends 'base.html' %}

{% block navbar %}
<nav class="navbar navbar-expand-sm bg-light">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('backoffice.home') }}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('backoffice.search_trip') }}"><i class="bi bi-search "></i> Backoffice: Buscar</a>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Admin
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('home') }}">Usuario</a>
            </div>
        </li>
    </ul>
</nav> 
{% endblock %}

{% block body %}
<div class="d-flex justify-content-center">
    <img src="{{url_for('static', filename='home.jpeg')}}" class="img-fluid" alt="CarpooleArg">
</div>

<div class="container d-flex justify-content-center">

    <div class="card shadow mr-5">
        <div class="card-body" style="color: cornflowerblue;">
            <i class="bi bi-search "></i> Backoffice: Buscar
        </div>
        <a href="{{ url_for('backoffice.search_trip') }}" class="stretched-link"></a>
    </div>
</div>
{% endblock %}


{% block script %}
{% endblock %}